package com.modules;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

import org.testng.Assert;

import com.pageObjects.CheckoutObjects;
import com.pageObjects.GlobalHeaderObjects;
import com.pageObjects.HomePageObjects;
import com.pageObjects.LoginObjects;
import com.pageObjects.MiniCartObjects;
import com.pageObjects.MyAccountObjects;
import com.pageObjects.PLPObjects;
import com.pageObjects.ShoppingCartObjects;
import com.pageObjects.SignUpObjects;
import com.pageObjects.UATObjects;
import com.utility.BrowserUtils;
import com.utility.Environments;
import com.utility.WebdriverUtils;

public class UATActions {
	public static void CreateUserFromPaymentSection() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				WebdriverUtils.goToURL(Environments.getUAT_URL());
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 15);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 10);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(ShoppingCartObjects.emailPopUP(), 10);
				WebdriverUtils.sendKeys(ShoppingCartObjects.guestEmail(), WebdriverUtils.generateRandomEmail());
				WebdriverUtils.clickAction(ShoppingCartObjects.checkBoxForNewsletters());
				WebdriverUtils.clickAction(ShoppingCartObjects.nextButton());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 10);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    Thread.sleep(2000);
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    Thread.sleep(2000);
			    WebdriverUtils.swipeDownUntillElement(UATObjects.AccountLink());
			    WebdriverUtils.clickAction(UATObjects.AccountLink());
			    BrowserUtils.waitFor(UATObjects.FirstName(), 10);
			    WebdriverUtils.sendKeys(UATObjects.FirstName(), pro.getProperty("signUpFirstName"));
			    WebdriverUtils.sendKeys(UATObjects.LastName(), pro.getProperty("signUpFirstName"));
				String email=WebdriverUtils.generateRandomEmail();
				WebdriverUtils.sendKeys(SignUpObjects.signUpEmailAddress(),email );
			    WebdriverUtils.sendKeys(UATObjects.Password(), pro.getProperty("Password"));
			    WebdriverUtils.sendKeys(UATObjects.ConfirmPassword(), pro.getProperty("Password"));
			    WebdriverUtils.clickAction(UATObjects.RegisterButton());
			    BrowserUtils.waitFor(UATObjects.CheckoutLogo(), 10);
			    WebdriverUtils.clickAction(UATObjects.CheckoutLogo());
			    BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 18);
				Assert.assertEquals(LoginObjects.MyAccountLink().getText().trim(), "My Account");
				WebdriverUtils.clickAction(MyAccountObjects.logoutLink());
				BrowserUtils.waitFor(LoginObjects.LogInLink(), 10);
				WebdriverUtils.clickAction(LoginObjects.LogInLink());
				BrowserUtils.waitFor(LoginObjects.EmailField(), 10);
				WebdriverUtils.sendKeys(LoginObjects.EmailField(),email );
				WebdriverUtils.sendKeys(LoginObjects.PasswordField(), pro.getProperty("Password"));
				WebdriverUtils.clickAction(LoginObjects.LogInButton());
				BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 20);
				Assert.assertEquals(LoginObjects.MyAccountLink().getText().trim(), "My Account");
	}
	
	public static void GiftMessageDisplay() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				Thread.sleep(500);
				SignUpActions.CreateNewAccount();
				Thread.sleep(1000);;
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 10);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 10);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    BrowserUtils.waitFor(CheckoutObjects.giftMessageTextField(), 10);
			    WebdriverUtils.sendKeys(CheckoutObjects.giftMessageTextField(), pro.getProperty("GiftMessage"));
			    BrowserUtils.waitFor(CheckoutObjects.giftDisplayTextField(), 10);
			    String GiftMessage=CheckoutObjects.giftDisplayTextField().getText().trim();
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    BrowserUtils.waitFor(UATObjects.OrderconfirmationGiftMessage(), 10);			    
			    Assert.assertEquals(UATObjects.OrderconfirmationGiftMessage().getText().trim(),GiftMessage);
	}
	
	public static void OrderConfirmationPopupDisplay() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				Thread.sleep(500);
				SignUpActions.CreateNewAccount();
				Thread.sleep(1000);
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 10);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 10);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    BrowserUtils.waitFor(UATObjects.OrderconfirmationPopup(), 15);
			    System.out.println(UATObjects.OrderconfirmationPopup().getText().trim());
			    Assert.assertEquals(UATObjects.OrderconfirmationPopup().getText().trim(), "Help us make Jelly Belly even better!");	      
	}
	
	public static void OrderConfirmationElementsDisplay() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				WebdriverUtils.goToURL(Environments.getUAT_URL());
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 15);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				String ProductName=PLPObjects.PLPProductName(pro.getProperty("UATProductName")).getText().trim();
				String Quantity=WebdriverUtils.getTextOfSelectedItem(PLPObjects.Quantity(pro.getProperty("UATProductName")));
				Double Price=Double.parseDouble(PLPObjects.Price(pro.getProperty("UATProductName")).getText().replace("$", "").trim());
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				Thread.sleep(1000);
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(ShoppingCartObjects.emailPopUP(), 15);
				String email=WebdriverUtils.generateRandomEmail();
				WebdriverUtils.sendKeys(ShoppingCartObjects.guestEmail(), email);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkBoxForNewsletters());
				WebdriverUtils.clickAction(ShoppingCartObjects.nextButton());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 10);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());			
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					String zipcode=UATObjects.CheckoutZipcode().getText().trim();
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
				Thread.sleep(500);
			    Double SubTotal=Double.parseDouble(CheckoutObjects.SubTotal().getText().replace("$", "").trim());
				Double Shipping=Double.parseDouble(CheckoutObjects.ShippingMethodsPriceInOrderSummary().getText().replace("$", "").trim());
				Thread.sleep(500);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.couponCodeInputField());
			    WebdriverUtils.sendKeys(CheckoutObjects.couponCodeInputField(), pro.getProperty("couponCode"));
			    WebdriverUtils.clickAction(CheckoutObjects.couponCodeApplyButton());
			    Thread.sleep(1500);				
				Double Coupon=Double.parseDouble(CheckoutObjects.CouponApplied().getText().replace("-$", "").trim());
				Double Total=Double.parseDouble(UATObjects.Total().getText().replace("$", "").trim());
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    BrowserUtils.waitFor(UATObjects.OrderconfirmationPopupClose(), 15);
			    WebdriverUtils.clickAction(UATObjects.OrderconfirmationPopupClose());
			    BrowserUtils.waitFor(UATObjects.BillingInfo(), 15);
			    System.out.println(UATObjects.OrderNumber().getText().trim());
			    Assert.assertTrue(UATObjects.OrderNumberText().getText().trim().contains("Your order number is "));
			    Assert.assertTrue(UATObjects.BillingInfo().isDisplayed());
			    Assert.assertEquals(UATObjects.BillingEmail().getText().trim(), email);
			    Assert.assertEquals(UATObjects.BillingName().getText().trim(), pro.getProperty("ShippingFirstName")+" "+pro.getProperty("ShippingLastName"));
			    Assert.assertEquals(UATObjects.BillingAddressName().getText().trim(), pro.getProperty("ShippingFirstName")+" "+pro.getProperty("ShippingLastName"));
			    Assert.assertEquals(UATObjects.BillingAddressLine1().getText().trim().toUpperCase(), pro.getProperty("ShippingAddressFirst").replace("drive", "Dr").toUpperCase().trim());
			    Assert.assertEquals(UATObjects.BillingAddressLine2().getText().trim(), pro.getProperty("ShippingAddressSecond"));
			    Assert.assertEquals(UATObjects.BillingCompany().getText().trim(), pro.getProperty("CompanyName"));
			    Assert.assertEquals(UATObjects.BillingZipcode().getText().trim().toUpperCase(),zipcode.trim().toUpperCase());
			    Assert.assertEquals(UATObjects.BillingPhoneNumber().getText().trim().replace("(", "").replace(")", "").replace(" ", "").replace("-", ""), pro.getProperty("ShippingPhoneNumber"));
			    Assert.assertEquals(UATObjects.CardType().getText().trim(), pro.getProperty("Cardtype").toUpperCase());
			    Assert.assertEquals(UATObjects.CardNumber().getText().trim(), pro.getProperty("EncryptedCardNumber"));
			    Assert.assertTrue(UATObjects.ShippingInfo().isDisplayed());
			    for(int i=0 ; i < UATObjects.shippingAddressLines().size() ;i++){
			    	Assert.assertEquals(UATObjects.shippingAddressLines().get(i).getText().trim(), UATObjects.BillingAddressLines().get(i).getText().trim());
			    }
			    Assert.assertTrue(UATObjects.PaymentInfo().getText().trim().contains("Credit Card"));
			    Assert.assertEquals(UATObjects.ProductName().getText().trim(), ProductName);
			    Assert.assertEquals(UATObjects.Quantity().getText().trim(), Quantity);
			    Assert.assertEquals((UATObjects.Price().getText().replace("$", "").trim()), Price);
			    Assert.assertEquals((UATObjects.SubTotal().getText().replace("$", "").trim()), SubTotal);
			    Assert.assertEquals((UATObjects.Shipping().getText().trim().replace("$", "")), Shipping);
			    Assert.assertEquals((UATObjects.Coupon().getText().trim().replace("-$", "")), Coupon);
			    Assert.assertEquals((UATObjects.Total().getText().replace("$", "").trim()), Total);
	}			    
	
	public static void ContinueShoppingNavigation() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				SignUpActions.CreateNewAccount();
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 10);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 10);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    BrowserUtils.waitFor(UATObjects.ContinueShopping(), 15);
			    WebdriverUtils.clickAction(UATObjects.ContinueShopping());
			    BrowserUtils.waitFor(GlobalHeaderObjects.jellyBellyLogo(), 15);
			    Assert.assertEquals(WebdriverUtils.getPageTitle().trim(), "Jelly Belly Candy Company | Official Website & Online Candy Store");	    
	}	
	
	public static void ProductInfoDisplay() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				SignUpActions.CreateNewAccount();
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 15);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				String ProductName=PLPObjects.PLPProductName(pro.getProperty("UATProductName")).getText().trim();
				String Quantity=WebdriverUtils.getTextOfSelectedItem(PLPObjects.Quantity(pro.getProperty("UATProductName")));
				String Price=PLPObjects.Price(pro.getProperty("UATProductName")).getText().replace("$", "").trim();
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 15);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    Thread.sleep(1000);
			    BrowserUtils.waitFor(UATObjects.OrderconfirmationPopupClose(), 10);
			    WebdriverUtils.clickAction(UATObjects.OrderconfirmationPopupClose());
			    Assert.assertEquals(UATObjects.ProductName().getText().trim(), ProductName);
			    Assert.assertEquals(UATObjects.Quantity().getText().trim(), Quantity);
			    WebdriverUtils.swipeDownUntillElement(UATObjects.Price());
			    System.out.println(UATObjects.Price().getText().replace("$", "").trim());
			    Assert.assertEquals(UATObjects.Price().getText().replace("$", "").trim(), Price);
	}
	
	public static void MyOrdersDisplay() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				String email=SignUpActions.CreateNewAccount();
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 15);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				String ProductName=PLPObjects.PLPProductName(pro.getProperty("UATProductName")).getText().trim();
				String Quantity=WebdriverUtils.getTextOfSelectedItem(PLPObjects.Quantity(pro.getProperty("UATProductName")));
				String Price=PLPObjects.Price(pro.getProperty("UATProductName")).getText().replace("$", "").trim();
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 15);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					String zipcode=UATObjects.CheckoutZipcode().getText().trim();
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    Double SubTotal=Double.parseDouble(CheckoutObjects.SubTotal().getText().replace("$", "").trim());
			    String Total=UATObjects.Total().getText().replace("$", "").trim();
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    Thread.sleep(1000);
			    BrowserUtils.waitFor(UATObjects.OrderconfirmationPopupClose(), 10);
			    WebdriverUtils.clickAction(UATObjects.OrderconfirmationPopupClose());
			    Assert.assertEquals(UATObjects.ProductName().getText().trim(), ProductName);
			    Assert.assertEquals(UATObjects.Quantity().getText().trim(), Quantity);
			    WebdriverUtils.swipeDownUntillElement(UATObjects.Price());
			    System.out.println(UATObjects.Price().getText().replace("$", "").trim());
			    Assert.assertEquals(UATObjects.Price().getText().replace("$", "").trim(), Price);
			    String OrderNumber=UATObjects.OrderNumber().getText().trim();			    
			    Assert.assertEquals(UATObjects.BillingEmail().getText().trim(), email);
			    Assert.assertEquals(UATObjects.BillingName().getText().trim(), pro.getProperty("ShippingFirstName")+" "+pro.getProperty("ShippingLastName"));
			    Assert.assertEquals(UATObjects.BillingAddressName().getText().trim(), pro.getProperty("ShippingFirstName")+" "+pro.getProperty("ShippingLastName"));
			    Assert.assertEquals(UATObjects.BillingAddressLine1().getText().trim().toUpperCase(), pro.getProperty("ShippingAddressFirst").replace("drive", "Dr").toUpperCase().trim());
			    Assert.assertEquals(UATObjects.BillingAddressLine2().getText().trim(), pro.getProperty("ShippingAddressSecond"));
			    Assert.assertEquals(UATObjects.BillingCompany().getText().trim(), pro.getProperty("CompanyName"));
			    Assert.assertEquals(UATObjects.BillingZipcode().getText().trim().toUpperCase(),zipcode.trim().toUpperCase());
			    Assert.assertEquals(UATObjects.BillingPhoneNumber().getText().trim().replace("(", "").replace(")", "").replace(" ", "").replace("-", ""), pro.getProperty("ShippingPhoneNumber"));
			    for(int i=0 ; i < UATObjects.shippingAddressLines().size() ;i++){
			    	Assert.assertEquals(UATObjects.shippingAddressLines().get(i).getText().trim(), UATObjects.BillingAddressLines().get(i).getText().trim());
			    }
			    Assert.assertEquals((UATObjects.SubTotal().getText().replace("$", "").trim()), SubTotal);
			    Thread.sleep(500);
			    BrowserUtils.waitFor(UATObjects.ContinueShopping(), 15);
			    WebdriverUtils.clickAction(UATObjects.ContinueShopping());
			    BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 10);
			    WebdriverUtils.clickAction(LoginObjects.MyAccountLink());
			    Thread.sleep(1000);
			    BrowserUtils.waitFor(UATObjects.MyOrdersLink(), 15);
			    WebdriverUtils.clickAction(UATObjects.MyOrdersLink());
			    BrowserUtils.waitFor(UATObjects.MyAccountOrderNumber(), 10);
			    Assert.assertEquals(UATObjects.MyAccountOrderNumber().getText().trim(), OrderNumber);
			    WebdriverUtils.clickAction(UATObjects.MyAccountOrderNumber());
			    BrowserUtils.waitFor(UATObjects.MyAccountEmail(), 10);
			    Assert.assertEquals(UATObjects.MyAccountEmail().getText().trim(), email);
			    Assert.assertEquals(UATObjects.MyAccountBillingName().getText().trim(), UATObjects.BillingName().getText().trim(),pro.getProperty("ShippingFirstName")+" "+pro.getProperty("ShippingLastName"));
	   		    Assert.assertEquals(UATObjects.MyAccountBillingAddressName().getText().trim(),UATObjects.BillingAddressName().getText().trim(), pro.getProperty("ShippingFirstName")+" "+pro.getProperty("ShippingLastName"));
			    Assert.assertEquals(UATObjects.MyAccountAddressLine1().getText().trim().toUpperCase(),UATObjects.BillingAddressLine1().getText().trim().toUpperCase(), pro.getProperty("ShippingAddressFirst").replace("drive", "Dr").toUpperCase().trim());
			    Assert.assertEquals(UATObjects.MyAccountAddressLine2().getText().trim(),UATObjects.BillingAddressLine2().getText().trim(), pro.getProperty("ShippingAddressSecond"));
			    Assert.assertEquals(UATObjects.MyAccountAddressCompany().getText().trim(),UATObjects.BillingCompany().getText().trim(), pro.getProperty("CompanyName"));
			    Assert.assertEquals(UATObjects.MyAccountZipcode().getText().trim().toUpperCase(), UATObjects.BillingZipcode().getText().trim().toUpperCase(),zipcode.trim().toUpperCase());
			    Assert.assertEquals(UATObjects.MyAccountPhoneNumber().getText().trim().replace("(", "").replace(")", "").replace(" ", "").replace("-", ""), UATObjects.BillingPhoneNumber().getText().trim().replace("(", "").replace(")", "").replace(" ", "").replace("-", ""), pro.getProperty("ShippingPhoneNumber"));
			    for(int i=0 ; i < UATObjects.MyAccountShippingAddressLines().size() ;i++){
			    	Assert.assertEquals(UATObjects.MyAccountShippingAddressLines().get(i).getText().trim(), UATObjects.MyAccountBillingAddressLines().get(i).getText().trim());
			    }
			    Assert.assertEquals(UATObjects.MyAccountCardType().getText().trim(),UATObjects.CardType().getText().trim(), pro.getProperty("Cardtype").toUpperCase());
			    Assert.assertEquals(UATObjects.MyAccountCardNumber().getText().trim(),UATObjects.CardNumber().getText().trim(), pro.getProperty("EncryptedCardNumber"));
			    Thread.sleep(4000);
//			    WebdriverUtils.swipeDownUntillElement(UATObjects.MyAccountProductName());
			    WebdriverUtils.scrollToElement("800");
			    System.out.println(UATObjects.MyAccountProductName().getText().trim());
			    Assert.assertEquals(UATObjects.MyAccountProductName().getText().trim(), ProductName );
			    System.out.println(UATObjects.MyAccountQuantity().getAttribute("quickorderquantity").trim());
			    Assert.assertEquals(UATObjects.MyAccountQuantity().getAttribute("quickorderquantity").trim(), Quantity.trim());
			    Assert.assertEquals(UATObjects.MyAccountTotal().getText().replace("$", "").trim(),Total.trim());
		}
	
	public static void NoOrdersTextDisplay() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				SignUpActions.CreateNewAccount();
				BrowserUtils.waitFor(UATObjects.MyOrdersLink(), 10);
				WebdriverUtils.clickAction(UATObjects.MyOrdersLink());
				BrowserUtils.waitFor(UATObjects.NoOrdersText(), 10);
				Assert.assertEquals(UATObjects.NoOrdersText().getText().trim(), "You have not placed any orders.");
	}
	
	public static void AddAllFunctionality() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				SignUpActions.CreateNewAccount();
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 15);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.shoppingCartHeader(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 10);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    Thread.sleep(1000);
			    BrowserUtils.waitFor(UATObjects.OrderconfirmationPopupClose(), 10);
			    WebdriverUtils.clickAction(UATObjects.OrderconfirmationPopupClose());
			    WebdriverUtils.swipeDownUntillElement(UATObjects.Price());
//			    System.out.println(UATObjects.Price().getText().replace("$", "").trim());
			    BrowserUtils.waitFor(UATObjects.ContinueShopping(), 15);
			    WebdriverUtils.clickAction(UATObjects.ContinueShopping());
			    BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 10);
			    WebdriverUtils.clickAction(LoginObjects.MyAccountLink());
			    Thread.sleep(2000);
			    BrowserUtils.waitFor(UATObjects.MyOrdersLink(), 15);
			    WebdriverUtils.clickAction(UATObjects.MyOrdersLink());
			    BrowserUtils.waitFor(UATObjects.OrderNumberText(), 15);
			    WebdriverUtils.clickAction(UATObjects.MyAccountOrderNumber());
			    BrowserUtils.waitFor(UATObjects.AddAllButton(), 10);
			    String ProductName = UATObjects.MyAccountProductName().getText().trim();
			    WebdriverUtils.clickAction(UATObjects.AddAllButton());
			    Thread.sleep(1000);
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.moveToElementByActions(GlobalHeaderObjects.cartCount());
				Thread.sleep(500);
				Assert.assertEquals(MiniCartObjects.MinicartProduct().getText().trim(), ProductName);
	}
	
	public static void AddToCartFunctionality() throws IOException, Exception{
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
				Properties pro = new Properties();
				pro.load(fs);
				SignUpActions.CreateNewAccount();
				BrowserUtils.waitFor(HomePageObjects.MegaMenu(), 10);
				WebdriverUtils.moveToElementByActions(HomePageObjects.MegaMenu());
				BrowserUtils.waitFor(PLPObjects.MenuLink(pro.getProperty("CategoryName")), 10);
				WebdriverUtils.clickAction(PLPObjects.MenuLink(pro.getProperty("CategoryName")));
				BrowserUtils.waitFor(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")), 15);
				WebdriverUtils.swipeDownUntillElement(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				WebdriverUtils.clickAction(PLPObjects.PLPAddToCart(pro.getProperty("UATProductName")));
				Thread.sleep(1000);
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.clickAction(GlobalHeaderObjects.cartCount());
				BrowserUtils.waitFor(ShoppingCartObjects.checkoutButtonTop(), 10);
				WebdriverUtils.clickAction(ShoppingCartObjects.checkoutButtonTop());
				BrowserUtils.waitFor(CheckoutObjects.CheckoutPageHeader(), 15);
				Assert.assertTrue(CheckoutObjects.CheckoutPageHeader().isDisplayed());
				WebdriverUtils.sendKeys(CheckoutObjects.companyName(), pro.getProperty("CompanyName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingFirstName(), pro.getProperty("ShippingFirstName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingLastName(), pro.getProperty("ShippingLastName"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineFirst(), pro.getProperty("ShippingAddressFirst"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressLineSecond(), pro.getProperty("ShippingAddressSecond"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressCity(), pro.getProperty("ShippingCity"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressState(), pro.getProperty("ShippingState"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingAddressZipCode(), pro.getProperty("ShippingZipcode"));
				WebdriverUtils.sendKeys(CheckoutObjects.shippingPhoneNumber(), pro.getProperty("ShippingPhoneNumber"));
				WebdriverUtils.selectByValue(CheckoutObjects.shippingAddressType(), pro.getProperty("ShippingAddresstype"));
				Thread.sleep(2000);
				if(CheckoutObjects.iframeBlocks().size()>0)
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					Thread.sleep(2000);
					WebdriverUtils.clickAction(CheckoutObjects.continueShippingMethods());
					BrowserUtils.waitFor(CheckoutObjects.shippingAddressEdit(), 10);
				WebdriverUtils.swipeDownUntillElement(CheckoutObjects.ShippingMethodLabel());
			    WebdriverUtils.clickAction(CheckoutObjects.ShippingMethods().get(0));
			    WebdriverUtils.clickAction(CheckoutObjects.continueToPaymentOptions());
			    BrowserUtils.waitFor(CheckoutObjects.paymentSection(), 10);
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.cardType());
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardType(), pro.getProperty("Cardtype"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardNumber(), pro.getProperty("Cardnumber"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardName(), pro.getProperty("Nameoncard"));
			    WebdriverUtils.selectByIndex(CheckoutObjects.cardExpirationMonth(), 2);
			    WebdriverUtils.selectByVisibleText(CheckoutObjects.cardExpirationYear(), pro.getProperty("Year"));
			    WebdriverUtils.sendKeys(CheckoutObjects.cardCVV(), pro.getProperty("CVV"));
			    WebdriverUtils.swipeDownUntillElement(CheckoutObjects.copyBillingToShipping());
			    WebdriverUtils.clickAction(CheckoutObjects.copyBillingToShipping());
			    BrowserUtils.waitFor(CheckoutObjects.editBilingInfo(), 10);
			    WebdriverUtils.clickAction(CheckoutObjects.nextReviewButton());
			    BrowserUtils.waitFor(CheckoutObjects.reviewOrderDescription(), 10);
			    WebdriverUtils.clickAction(UATObjects.PlaceOrder());
			    Thread.sleep(1000);
			    BrowserUtils.waitFor(UATObjects.OrderconfirmationPopupClose(), 15);
			    WebdriverUtils.clickAction(UATObjects.OrderconfirmationPopupClose());
			    Thread.sleep(500);
			    WebdriverUtils.swipeDownUntillElement(UATObjects.Price());
			    System.out.println(UATObjects.Price().getText().replace("$", "").trim());
			    BrowserUtils.waitFor(UATObjects.ContinueShopping(), 15);
			    WebdriverUtils.clickAction(UATObjects.ContinueShopping());
			    BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 15);
			    WebdriverUtils.clickAction(LoginObjects.MyAccountLink());
			    Thread.sleep(1000);
			    BrowserUtils.waitFor(UATObjects.MyOrdersLink(), 15);
			    WebdriverUtils.clickAction(UATObjects.MyOrdersLink());
			    BrowserUtils.waitFor(UATObjects.MyAccountOrderNumber(), 10);
			    WebdriverUtils.clickAction(UATObjects.MyAccountOrderNumber());
			    BrowserUtils.waitFor(UATObjects.MyAccounttAddToCart(), 10);
			    String ProductName = UATObjects.MyAccountProductName().getText().trim();
			    WebdriverUtils.clickAction(UATObjects.MyAccounttAddToCart());
			    Thread.sleep(1000);
				WebdriverUtils.waitUntilValuePresentInElement(GlobalHeaderObjects.cartCount(), "1");
				Assert.assertEquals(GlobalHeaderObjects.cartCount().getText().trim(), "1");
				WebdriverUtils.moveToElementByActions(GlobalHeaderObjects.cartCount());
				Thread.sleep(500);
				Assert.assertEquals(MiniCartObjects.MinicartProduct().getText().trim(), ProductName);
	}
	
	public static void StoreCreditStaticContentDisplay() throws IOException, Exception {
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
		Properties pro = new Properties();
		pro.load(fs);
		WebdriverUtils.goToURL(Environments.getUAT_URL());
		BrowserUtils.waitFor(LoginObjects.LogInLink(), 10);
		WebdriverUtils.clickAction(LoginObjects.LogInLink());
		BrowserUtils.waitFor(LoginObjects.EmailField(), 10);
		WebdriverUtils.sendKeys(LoginObjects.EmailField(), pro.getProperty("Email"));
		WebdriverUtils.sendKeys(LoginObjects.PasswordField(), pro.getProperty("Password"));
		WebdriverUtils.clickAction(LoginObjects.LogInButton());
		BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 15);
		WebdriverUtils.clickAction(LoginObjects.MyAccountLink());
		BrowserUtils.waitFor(UATObjects.StorecreditLink(), 10);
		WebdriverUtils.clickAction(UATObjects.StorecreditLink());
		BrowserUtils.waitFor(UATObjects.StorecreditStaticContent(), 10);
		Assert.assertTrue(UATObjects.StorecreditStaticContent().getText().trim().contains("CLAIMING YOUR GIFT CERTIFICATE IS EASY!"));
		Assert.assertTrue(UATObjects.StorecreditStaticContent1().getText().trim().contains("You currently have a gift certificate balance"));
	}
	
	public static void StoreCreditDisplay() throws IOException, Exception {
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
		Properties pro = new Properties();
		pro.load(fs);
		WebdriverUtils.goToURL(Environments.getUAT_URL());
		BrowserUtils.waitFor(LoginObjects.LogInLink(), 10);
		WebdriverUtils.clickAction(LoginObjects.LogInLink());
		BrowserUtils.waitFor(LoginObjects.EmailField(), 10);
		WebdriverUtils.sendKeys(LoginObjects.EmailField(), pro.getProperty("Email"));
		WebdriverUtils.sendKeys(LoginObjects.PasswordField(), pro.getProperty("Password"));
		WebdriverUtils.clickAction(LoginObjects.LogInButton());
		BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 15);
		WebdriverUtils.clickAction(LoginObjects.MyAccountLink());
		BrowserUtils.waitFor(UATObjects.StorecreditLink(), 10);
		WebdriverUtils.clickAction(UATObjects.StorecreditLink());
		BrowserUtils.waitFor(UATObjects.GiftCardTextField(), 10);
		Assert.assertTrue(UATObjects.GiftCardTextField().isDisplayed());
		Assert.assertEquals(UATObjects.ApplyButton().getText().trim(),"APPLY");
	}
	
	public static void GiftCardErrorMessageDisplay() throws IOException, Exception {
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
		Properties pro = new Properties();
		pro.load(fs);
		WebdriverUtils.goToURL(Environments.getUAT_URL());
		BrowserUtils.waitFor(LoginObjects.LogInLink(), 10);
		WebdriverUtils.clickAction(LoginObjects.LogInLink());
		BrowserUtils.waitFor(LoginObjects.EmailField(), 10);
		WebdriverUtils.sendKeys(LoginObjects.EmailField(), pro.getProperty("Email"));
		WebdriverUtils.sendKeys(LoginObjects.PasswordField(), pro.getProperty("Password"));
		WebdriverUtils.clickAction(LoginObjects.LogInButton());
		BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 15);
		WebdriverUtils.clickAction(LoginObjects.MyAccountLink());
		BrowserUtils.waitFor(UATObjects.StorecreditLink(), 10);
		WebdriverUtils.clickAction(UATObjects.StorecreditLink());
		BrowserUtils.waitFor(UATObjects.GiftCardTextField(), 10);
		WebdriverUtils.sendKeys(UATObjects.GiftCardTextField(), "Testing");
		WebdriverUtils.clickAction(UATObjects.ApplyButton());
		BrowserUtils.waitFor(UATObjects.GiftCardErrorMessage(), 10);
		Assert.assertTrue(UATObjects.GiftCardErrorMessage().getText().trim().contains("Please be sure that you're using the correct code"));
	}
	
	public static void StoreCreditElementsDisplay() throws IOException, Exception {
		FileInputStream fs = new FileInputStream(
				System.getProperty("user.dir") + "//src//com//config//config.properties");
		Properties pro = new Properties();
		pro.load(fs);
		WebdriverUtils.goToURL(Environments.getUAT_URL());
		BrowserUtils.waitFor(LoginObjects.LogInLink(), 10);
		WebdriverUtils.clickAction(LoginObjects.LogInLink());
		BrowserUtils.waitFor(LoginObjects.EmailField(), 10);
		WebdriverUtils.sendKeys(LoginObjects.EmailField(), pro.getProperty("Email"));
		WebdriverUtils.sendKeys(LoginObjects.PasswordField(), pro.getProperty("Password"));
		WebdriverUtils.clickAction(LoginObjects.LogInButton());
		BrowserUtils.waitFor(LoginObjects.MyAccountLink(), 15);
		WebdriverUtils.clickAction(LoginObjects.MyAccountLink());
		BrowserUtils.waitFor(UATObjects.StorecreditLink(), 10);
		WebdriverUtils.clickAction(UATObjects.StorecreditLink());
		BrowserUtils.waitFor(UATObjects.StoreCreditCode(), 10);
		Assert.assertTrue(UATObjects.StoreCreditCode().isDisplayed());
		Assert.assertTrue(UATObjects.CreditDate().isDisplayed());
		Assert.assertTrue(UATObjects.CreditAmount().isDisplayed());
		Assert.assertTrue(UATObjects.RemainingAmount().isDisplayed());
		Assert.assertTrue(UATObjects.TotalCreditBalance().isDisplayed());
	
	}
}

